name: CI

on:
  push:
    branches: [ master ]

jobs:
  build:
    # windows-latest or windows-2019
    # ubuntu-20.04
    # ubuntu-latest or ubuntu-18.04
    # ubuntu-16.04
    # macos-latest or macos-10.15
    runs-on: ubuntu-latest

    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    # - uses: actions/checkout@v2

    - name: Run a multi-line script
      run: |
        echo pwd
        echo ls -la
        echo sudo apt-get search mingw
