name: CI

on:
  push:
    branches: [ actions ]

jobs:
  build:
    # windows-latest or windows-2019
    # ubuntu-20.04
    # ubuntu-latest or ubuntu-18.04
    # ubuntu-16.04
    # macos-latest or macos-10.15
    runs-on: ubuntu-latest

    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    # - uses: actions/checkout@v2
    steps:
      - name: Print dir tree
        run: sudo ls -RAmp /
      - name: See if mingw is installable #1
        run: which apt
      - name: See if mingw is installable
        run: sudo apt-cache search mingw
